"""initial migration

Revision ID: 83102813d32d
Revises: 
Create Date: 2019-03-05 15:30:54.995091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83102813d32d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('demand',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('address', sa.VARCHAR(length=20), nullable=True),
    sa.Column('channel', sa.INTEGER(), nullable=True),
    sa.Column('circuit', sa.VARCHAR(length=20), nullable=True),
    sa.Column('model', sa.VARCHAR(length=20), nullable=True),
    sa.Column('datetime', sa.DATETIME(), nullable=True),
    sa.Column('demand_min', sa.FLOAT(precision='20,2'), nullable=True),
    sa.Column('demand_quarter', sa.FLOAT(precision='20,2'), nullable=True),
    sa.Column('R_value', sa.FLOAT(precision='20,2'), nullable=True),
    sa.Column('S_value', sa.FLOAT(precision='20,2'), nullable=True),
    sa.Column('T_value', sa.FLOAT(precision='20,2'), nullable=True),
    sa.Column('Total_value', sa.FLOAT(precision='20,2'), nullable=True),
    sa.Column('gateway_uid', sa.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('demand_index', 'demand', ['datetime', 'address', 'channel'], unique=False)
    op.create_table('demand_settings',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('value', sa.INTEGER(), nullable=True),
    sa.Column('value_max', sa.INTEGER(), nullable=True),
    sa.Column('value_min', sa.INTEGER(), nullable=True),
    sa.Column('load_off_gap', sa.INTEGER(), nullable=True),
    sa.Column('reload_delay', sa.INTEGER(), nullable=True),
    sa.Column('reload_gap', sa.INTEGER(), nullable=True),
    sa.Column('cycle', sa.INTEGER(), nullable=True),
    sa.Column('mode', sa.VARCHAR(length=255), nullable=True),
    sa.Column('groups', sa.VARCHAR(length=255), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('electricity_information',
    sa.Column('user_id', sa.VARCHAR(length=20), nullable=False),
    sa.Column('datetime', sa.DATETIME(), nullable=False),
    sa.Column('value', sa.FLOAT(), nullable=True),
    sa.Column('Global_active_power', sa.FLOAT(), nullable=True),
    sa.Column('Global_reactive_power', sa.FLOAT(), nullable=True),
    sa.Column('Voltage', sa.FLOAT(), nullable=True),
    sa.Column('Global_intensity', sa.FLOAT(), nullable=True),
    sa.Column('Sub_metering_1', sa.FLOAT(), nullable=True),
    sa.Column('Sub_metering_2', sa.FLOAT(), nullable=True),
    sa.Column('Sub_metering_3', sa.FLOAT(), nullable=True),
    sa.PrimaryKeyConstraint('user_id', 'datetime')
    )
    op.create_table('festival',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('date', sa.DATE(), nullable=True),
    sa.Column('statement', sa.VARCHAR(length=255), nullable=True),
    sa.Column('bind_table', sa.VARCHAR(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gateway',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('uid', sa.VARCHAR(length=255), nullable=True),
    sa.Column('country', sa.VARCHAR(length=20), nullable=True),
    sa.Column('city', sa.VARCHAR(length=20), nullable=True),
    sa.Column('physical_address', sa.VARCHAR(length=255), nullable=True),
    sa.Column('gateway_name', sa.VARCHAR(length=127), nullable=True),
    sa.Column('project_id', sa.VARCHAR(length=20), nullable=True),
    sa.Column('sunrise', sa.TIME(), nullable=True),
    sa.Column('sunset', sa.TIME(), nullable=True),
    sa.Column('lat', sa.VARCHAR(length=255), nullable=True),
    sa.Column('lng', sa.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('group',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('group_num', sa.INTEGER(), nullable=True),
    sa.Column('group_name', sa.VARCHAR(length=20), nullable=True),
    sa.Column('group_state', sa.VARCHAR(length=20), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('links',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('domain', sa.VARCHAR(length=255), nullable=True),
    sa.Column('ip', sa.VARCHAR(length=255), nullable=True),
    sa.Column('path', sa.VARCHAR(length=255), nullable=True),
    sa.Column('port', sa.VARCHAR(length=255), nullable=True),
    sa.Column('key', sa.VARCHAR(length=255), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('log',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('gateway_uid', sa.VARCHAR(length=255), nullable=True),
    sa.Column('action', sa.VARCHAR(length=20), nullable=True),
    sa.Column('content', sa.VARCHAR(length=64), nullable=True),
    sa.Column('data', sa.TEXT(), nullable=True),
    sa.Column('execute_state', sa.VARCHAR(length=64), nullable=True),
    sa.Column('datetime', sa.DATETIME(), nullable=True),
    sa.Column('role', sa.VARCHAR(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('offloads',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('group', sa.INTEGER(), nullable=True),
    sa.Column('hand_controls', sa.VARCHAR(length=20), nullable=True),
    sa.Column('offload_available', sa.VARCHAR(length=20), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('project_name', sa.VARCHAR(length=64), nullable=True),
    sa.Column('account', sa.VARCHAR(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scenes',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('node', sa.INTEGER(), nullable=True),
    sa.Column('node_state', sa.VARCHAR(length=10), nullable=True),
    sa.Column('scene_name', sa.VARCHAR(length=10), nullable=True),
    sa.Column('scene_number', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schedule',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('schedule_table', sa.VARCHAR(length=10), nullable=True),
    sa.Column('group_id', sa.INTEGER(), nullable=True),
    sa.Column('schedule_group_state', sa.VARCHAR(length=10), nullable=True),
    sa.Column('control_time', sa.TIME(), nullable=True),
    sa.Column('control_time_of_sun', sa.VARCHAR(length=10), nullable=True),
    sa.Column('setting', sa.VARCHAR(length=25), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('setting',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('model', sa.VARCHAR(length=20), nullable=True),
    sa.Column('address', sa.VARCHAR(length=20), nullable=True),
    sa.Column('ch', sa.VARCHAR(length=20), nullable=True),
    sa.Column('speed', sa.VARCHAR(length=20), nullable=True),
    sa.Column('circuit', sa.VARCHAR(length=20), nullable=True),
    sa.Column('pt', sa.VARCHAR(length=20), nullable=True),
    sa.Column('ct', sa.VARCHAR(length=20), nullable=True),
    sa.Column('meter_type', sa.VARCHAR(length=20), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('gateway_uid', sa.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('account', sa.VARCHAR(length=64), nullable=True),
    sa.Column('password', sa.VARCHAR(length=512), nullable=True),
    sa.Column('authority', sa.VARCHAR(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('weather',
    sa.Column('WindSpeed', sa.INTEGER(), nullable=True),
    sa.Column('Temperature', sa.FLOAT(), nullable=True),
    sa.Column('DateTime', sa.DATETIME(), nullable=False),
    sa.Column('RelHumidity', sa.FLOAT(), nullable=True),
    sa.Column('apparent_temperature', sa.FLOAT(), nullable=True),
    sa.PrimaryKeyConstraint('DateTime')
    )
    op.create_table('node',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('gateway', sa.VARCHAR(length=255), nullable=True),
    sa.Column('gateway_address', sa.VARCHAR(length=20), nullable=True),
    sa.Column('model', sa.VARCHAR(length=20), nullable=True),
    sa.Column('node_name', sa.VARCHAR(length=20), nullable=True),
    sa.Column('node', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('model_type', sa.INTEGER(), nullable=True),
    sa.Column('node_state', sa.VARCHAR(length=10), nullable=True),
    sa.Column('group_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('node')
    op.drop_table('weather')
    op.drop_table('user')
    op.drop_table('setting')
    op.drop_table('schedule')
    op.drop_table('scenes')
    op.drop_table('project')
    op.drop_table('offloads')
    op.drop_table('log')
    op.drop_table('links')
    op.drop_table('group')
    op.drop_table('gateway')
    op.drop_table('festival')
    op.drop_table('electricity_information')
    op.drop_table('demand_settings')
    op.drop_index('demand_index', table_name='demand')
    op.drop_table('demand')
    # ### end Alembic commands ###
